build(deps): bump com.google.devtools.ksp from 1.9.22-1.0.18 to 1.9.23-1.0.19 in /manager (#1487)
Bumps [com.google.devtools.ksp](https://github.com/google/ksp) from
1.9.22-1.0.18 to 1.9.23-1.0.19.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/google/ksp/releases">com.google.devtools.ksp's
releases</a>.</em></p>
<blockquote>
<h2>1.9.23-1.0.19</h2>
<h3>New APIs</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1708">#1708</a>
<code>SymbolProcessorEnvironment.kspVersion</code></li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1707">#1707</a>
<code>CodeGenerator.associateWithFunctions</code> and
<code>CodeGenerator.associateWithProperties</code></li>
</ul>
<h3>Issues fixed in KSP2</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1691">#1691</a>
IllegalStateException: Value type not found for value</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1719">#1719</a> The
order of symbols returned from Resolver.getSymbolsWithAnnotation() is
different</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1718">#1718</a>
Getting packageName of Kotlin types returns empty String</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1721">#1721</a>
KSAnnotation packageName is an empty String for a type from a different
module</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1722">#1722</a>
Resolver.getDeclarationsFromPackage() returns declarations from the
default package when passing in an unknown package</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1717">#1717</a>
Resolver.getJvmName() returns different results for annotation args</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1725">#1725</a>
asMemberOf() throws exception with a generic type without arguments</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1728">#1728</a>
ClassCastException when calling KSType.replace() with empty list</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1713">#1713</a>
NoClassDefFoundError for LZ4Factory when trying KSP2</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1665">#1665</a>
NoClassDefFound in ksp.useKSP2=true mode</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1733">#1733</a> ABI
incompatibility with kotlin-compiler-embeddable in 2.0.0-Beta4</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1714">#1714</a>
Generated resources are not added to KotlinCompilation inputs</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1747">#1747</a>
isCompanionObject is false for companion objects from KOTLIN_LIB</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1743">#1743</a>
Incorrect type parameter variances</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1759">#1759</a>
IllegalStateException when getting the modifiers from properties in a
Java annotation declaration</li>
</ul>
<h3>Issues fixed in KSP Gradle Plugin</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1712">#1712</a>
Analysis API artifacts have the wrong common-deps dependency</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1775">#1775</a>
1.0.18 creates circular dependencies with kapt tasks</li>
<li><a
href="https://redirect.github.com/google/ksp/issues/1772">#1772</a>
Update plugin com.google.devtools.ksp to v1.9.22-1.0.18 BUILD
FAILED</li>
</ul>
<h3>Known issues</h3>
<ul>
<li><a
href="https://redirect.github.com/google/ksp/issues/1776">#1776</a> KSP2
has higher memory usage when the compile classpath is very large.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/google/ksp/commits/1.9.23-1.0.19">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.google.devtools.ksp&package-manager=gradle&previous-version=1.9.22-1.0.18&new-version=1.9.23-1.0.19)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>