sched/fair: bore: pass load weight to reweight_task()
At some point, reweight_task() was updated to take in a load weight parameter instead of a priority integer. This led to an error like:

../kernel/sched/fair.c:159:20: error: incompatible integer to pointer conversion passing 'u8' (aka 'unsigned char') to parameter of type 'const struct load_weight *' [-Wint-conversion]
  159 |                 reweight_task(p, new_prio);
      |                                  ^~~~~~~~
../kernel/sched/sched.h:1925:76: note: passing argument to parameter 'lw' here
 1925 | extern void reweight_task(struct task_struct *p, const struct load_weight *lw);
      |                                                                            ^
1 error generated.

Correct the function call accordingly.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: dopaemon <polarisdp@gmail.com>