techpack: dataipa: !fixup: function declaration without a prototype is deprecated in all versions of C
techpack/dataipa/drivers/platform/msm/gsi/gsihal/gsihal_reg.c:2312:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 2312 | u32 gsihal_get_bit_map_array_size()
      |                                  ^
      |                                   void
techpack/dataipa/drivers/platform/msm/gsi/gsihal/gsihal_reg.c:2523:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 2523 | u32 gsihal_get_glob_irq_en_gp_int1_mask()
      |                                        ^
      |                                         void
2 errors generated.

Signed-off-by: dopaemon <polarisdp@gmail.com>