fs: ksmbd: fix check_add_overflow for 5.10
In 5.10, it expects a long variable type:

../fs/ksmbd/smbacl.c:1182:6: error: comparison of distinct pointer types ('typeof (dacloffset) *' (aka 'unsigned int *') and 'typeof (sizeof(struct smb_acl)) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
1182 |             check_add_overflow(dacloffset, sizeof(struct smb_acl), &dacl_struct_end) ||
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/overflow.h:70:15: note: expanded from macro 'check_add_overflow'
70 |         (void) (&__a == &__b);
|                 ~~~~ ^  ~~~~
../fs/ksmbd/smbacl.c:1182:6: error: comparison of distinct pointer types ('typeof (dacloffset) *' (aka 'unsigned int *') and 'typeof (&dacl_struct_end)' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
1182 |             check_add_overflow(dacloffset, sizeof(struct smb_acl), &dacl_struct_end) ||
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/overflow.h:71:15: note: expanded from macro 'check_add_overflow'
71 |         (void) (&__a == __d);
|                 ~~~~ ^  ~~~
../fs/ksmbd/smbacl.c:1421:6: error: comparison of distinct pointer types ('typeof (dacl_offset) *' (aka 'unsigned int *') and 'typeof (sizeof(struct smb_acl)) *' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
1421 |             check_add_overflow(dacl_offset, sizeof(struct smb_acl), &dacl_struct_end) ||
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/overflow.h:70:15: note: expanded from macro 'check_add_overflow'
70 |         (void) (&__a == &__b);
|                 ~~~~ ^  ~~~~
../fs/ksmbd/smbacl.c:1421:6: error: comparison of distinct pointer types ('typeof (dacl_offset) *' (aka 'unsigned int *') and 'typeof (&dacl_struct_end)' (aka 'unsigned long *')) [-Werror,-Wcompare-distinct-pointer-types]
1421 |             check_add_overflow(dacl_offset, sizeof(struct smb_acl), &dacl_struct_end) ||
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/overflow.h:71:15: note: expanded from macro 'check_add_overflow'
71 |         (void) (&__a == __d);
|                 ~~~~ ^  ~~~
4 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>